# Generated by Django 3.2.16 on 2023-04-16 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('person_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('surname', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phoneNumber', models.CharField(default='', max_length=20)),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.comment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
