# Generated by Django 3.2.16 on 2023-05-28 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('surname', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phoneNumber', models.CharField(default='', max_length=20)),
                ('manager_email', models.CharField(default='head.admin@gmail.com', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('surname', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phoneNumber', models.CharField(default='', max_length=20)),
                ('company', models.CharField(default='Bike Industries', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_field', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('surname', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phoneNumber', models.CharField(default='', max_length=20)),
                ('amount', models.FloatField(default=100.0)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('deactivated', 'Deactivated'), ('not_confirmed', 'Not Confirmed')], default='not_confirmed', max_length=13)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
