# Generated by Django 3.2.16 on 2023-05-08 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
        ('payment', '0001_initial'),
        ('authentication', '0002_worker_reservations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('person_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('surname', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phoneNumber', models.CharField(default='', max_length=20)),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.comment')),
                ('payments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
