# Generated by Django 3.2.16 on 2023-05-08 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
        ('reservation', '0001_initial'),
        ('payment', '0001_initial'),
        ('authentication', '0003_consumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='comments',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='comment.comment'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='payments',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='payment.payment'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='comments',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='comment.comment'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='reservations',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation'),
        ),
    ]
