# Generated by Django 3.2.16 on 2023-05-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20230508_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='payments',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='reservations',
        ),
        migrations.AddField(
            model_name='consumer',
            name='random_field',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='worker',
            name='another_field',
            field=models.CharField(default='', max_length=50),
        ),
    ]
