# Generated by Django 3.2.16 on 2023-04-16 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('comp_ID', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=300)),
                ('last_updated', models.DateTimeField()),
                ('status', models.CharField(choices=[('closed', 'Closed'), ('opened', 'Opened'), ('solved', 'Solved')], default='closed', max_length=6)),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.comment')),
            ],
        ),
    ]
