# Generated by Django 3.2.16 on 2023-04-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comm_ID', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
