# Generated by Django 3.2.16 on 2023-04-16 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_ID', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_date_request', models.DateTimeField()),
                ('reservation_date_end', models.DateTimeField()),
                ('reservationStatus', models.CharField(choices=[('confirmed', 'Confirmed'), ('not confirmed', 'Not Confirmed'), ('finished', 'Finished'), ('pending', 'Pending')], default='pending', max_length=13)),
                ('reserved_bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.bike')),
            ],
        ),
    ]
